name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag suffix'
        required: false
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            talha1dev/ai-studio:got-ocr-${{ steps.date.outputs.date }}-${{ github.event.inputs.tag || 'latest' }}
            talha1dev/ai-studio:got-ocr-latest
          cache-from: type=registry,ref=talha1dev/ai-studio:buildcache
          cache-to: type=registry,ref=talha1dev/ai-studio:buildcache,mode=max
